// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uygydxgmihsxajaksdcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z3lkeGdtaWhzeGFqYWtzZGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTA5ODYsImV4cCI6MjA2NTQ2Njk4Nn0.eaz-XcU0gzLvPa-ctBkswBuYfJKZkx920W-L3MJSof0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);